export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const ADD_TAG_GROUP = 'ADD_TAG_GROUP';
export const ADD_ARCHIVED_QUESTION_ID = 'ADD_ARCHIVED_QUESTION_ID';
export const ADD_ARCHIVED_QUESTION_IDS = 'ADD_ARCHIVED_QUESTION_IDS';
