export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const ADD_TAG_GROUP = 'ADD_TAG_GROUP';
export const ADD_ARCHIVED_QUESTION_ID = 'ADD_ARCHIVED_QUESTION_ID';
export const ADD_ARCHIVED_QUESTION_IDS = 'ADD_ARCHIVED_QUESTION_IDS';
export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER';
export const DECREMENT_PAGE_NUMBER = 'DECREMENT_PAGE_NUMBER';
